name: Update latest tag

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  update-latest:
    if: github.ref_name != 'latest'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Validate release and update latest tag
        run: |
          python scripts/update_latest_tag.py
      - name: Push latest tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git push origin latest --force
